### PR TITLE
Add Wait, Timeout, and Force to helm-release

### PR DESCRIPTION
**Pull request by chickenandpork**
In our desire to leverage `--wait` and `--force` in helm, we found that:
 - the `{WAIT}` token was present in the template for `echo` only, not the actual command
 - the `--timeout` wasn't there, but hey wouldn't that be useful for some of our longer deploys?
 - the `--force` was beneficial to have more authority over what helm does
 
 ...so I tried to fix the `{WAIT}` usage in the actual helm command execution, and plumbed-through the other options.
 
 I must admit, some of the commands seem to opine about use of strings over booleans, but honestly, there must have been reasons, so please don't be offended.
 
 We have this in production use right now, seems to be working, I hope you'll accept this PR to maintain a change that has benefitted us, and we can resume working off your `LATEST`.  Thanks!

### CODE REVIEW

**Comment by gutmox** [comment]
@danigar @pmoncadaisla

**Comment by chickenandpork** [comment]
@gutmox @danigar @pmoncadaisla I just pushed a rebase of this PR against your master branch, but the CI seems choked on an updated go toolchain?
```
51 go: finding github.com/google/safetext v0.0.0-20220905092116-b49f7bc46da2
52 build sigs.k8s.io/kind: cannot load io/fs: malformed module path "io/fs": missing dot in first path element
53 Error: Process completed with exit code 1.
```

Unsure how to unblock this PR; I've got anther PR waiting behind this one, and working on a addiction for OSX/arm64 toolchain after that.

**Comment by chickenandpork** [comment]
@gutmox @danigar @pmoncadaisla or anyone else I can convince to review: the issue with the workflows is resolved in two independent PRs to address each of the issues; on that, this PR adds the features I wrote last July.

all tests passing now, please take a look at this PR, and #49 and #50

**Review by danigar — APPROVED** [review]
Thanks @chickenandpork and sorry for the delay. g2g 👍 !!

**Pull request merged**
