### PR TITLE
Use namespace from kube context when namespace not supplied

### PR DESCRIPTION
**Pull request by marksmithson**
If the `namespace` attribute is not supplied to the rule helm is called with `--namespace=default`.

As a result the rule cannot be used to install the chart into the current namespace for the kubernetes context.

This MR prevents the `--namespace` argument being passed to helm when it is not specified.

This change could affect users who are relying on the chart being installed in the `default` namespace where their kube context specifies an alternative namespace to `default`. This is unlikely, however can be mitigated by users specifying `namespace="default"` when calling the rule

### CODE REVIEW

**Comment by pmoncadaisla** [comment]
Hi @marksmithson , thanks for your contribution! 🎉 

I have some concerns:

1. I'm not sure if relying on an external config not managed by Bazel is a deterministic approach. 
2. It is true that it is not backward-compatible, what about adding extra input attribute to the rule? (I.E. `use_kubecontext_namespace`)

Tell us what you think about this. Thanks!

**Comment by marksmithson** [comment]
> 1. I'm not sure if relying on an external config not managed by Bazel is a deterministic approach.

The generated chart and perhaps the installation script are what should be deterministic, not the effect of running these scripts in an external environment (outside of bazel). This change does not affect that - it is just that the NAMESPACE is `""` and not `default`

> It is true that it is not backward-compatible, what about adding extra input attribute to the rule? (I.E. use_kubecontext_namespace)

How about we just set the default for the namespace attribute to `"default"`? Users can then set this to `""` to use whatever default namespace is in their kubectl context? Would need a doc update as well.

( ideally the default would be "", but using "default" is a reasonable compromise for backward campatibility. )

Note that some clusters may have deleted the default namespace, so it may not be a great "default" :)

**Comment by marksmithson** [comment]
Done.

Fixed up some attribute names in docs whilst I was there.

Formatted version look like this:

image

**Review by pmoncadaisla — APPROVED** [review]
LGTM!

@danigar , feel free to merge!

**Pull request merged**
